package httpapi

import (
	"encoding/json"
	"net/http"
)

func (s *Server) handleAdminListMarketplace(w http.ResponseWriter, r *http.Request) {
	// Return ALL catalog items with caution labels for incomplete ones
	marketplaceItems := []map[string]interface{}{
		// Reasoning Category
		{
			"slug":          "sequential-thinking",
			"name":          "Sequential Thinking",
			"description":   "Step-by-step structured reasoning.",
			"category":      "Reasoning",
			"tags":          []string{"reasoning"},
			"version":       "1.0.0",
			"author":        "MCP Team",
			"repository":    "https://www.npmjs.com/package/@modelcontextprotocol/server-sequential-thinking",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "@modelcontextprotocol/server-sequential-thinking"},
			"configExample": "{ \"mcpServers\": { \"sequential-thinking\": { \"command\": \"npx\", \"args\": [\"-y\",\"@modelcontextprotocol/server-sequential-thinking\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "crash",
			"name":          "CRASH (Cascaded Reasoning)",
			"description":   "Confidence tracking, branching, adaptive steps.",
			"category":      "Reasoning",
			"tags":          []string{"reasoning", "confidence", "branching"},
			"version":       "1.0.0",
			"author":        "MCP Team",
			"repository":    "https://github.com/modelcontextprotocol/crash-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "crash-mcp"},
			"configExample": "{ \"mcpServers\": { \"crash\": { \"command\": \"npx\", \"args\": [\"-y\",\"crash-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "reasoner",
			"name":          "MCP Reasoner (Beam/MCTS)",
			"description":   "Beam search & MCTS reasoning.",
			"category":      "Reasoning",
			"tags":          []string{"reasoning", "beam-search", "mcts"},
			"version":       "1.0.0",
			"author":        "MCP Community",
			"repository":    "https://glama.ai/mcp/Reasoner",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "mcp-reasoner"},
			"configExample": "{ \"mcpServers\": { \"reasoner\": { \"command\": \"npx\", \"args\": [\"-y\",\"mcp-reasoner\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "mcts",
			"name":          "MCTS MCP",
			"description":   "Monte Carlo Tree Search.",
			"category":      "Reasoning",
			"tags":          []string{"reasoning", "mcts", "search"},
			"version":       "1.0.0",
			"author":        "MCP Community",
			"repository":    "https://github.com/search?q=MCTS+MCP+server",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "mcts-mcp"},
			"configExample": "{ \"mcpServers\": { \"mcts\": { \"command\": \"npx\", \"args\": [\"-y\",\"mcts-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "got",
			"name":          "Graph-of-Thoughts",
			"description":   "Graph reasoning (Neo4j optional).",
			"category":      "Reasoning",
			"tags":          []string{"reasoning", "graph", "neo4j"},
			"version":       "1.0.0",
			"author":        "MCP Community",
			"repository":    "https://github.com/saptadey/got-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "got-mcp"},
			"configExample": "{ \"mcpServers\": { \"got\": { \"command\": \"npx\", \"args\": [\"-y\",\"got-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "dre",
			"name":          "Deliberate Reasoning Engine (DRE)",
			"description":   "DAG / thought-graph reasoning.",
			"category":      "Reasoning",
			"tags":          []string{"reasoning", "dag", "thought-graph"},
			"version":       "1.0.0",
			"author":        "MCP Community",
			"repository":    "https://glama.ai/mcp/DRE",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "dre-mcp"},
			"configExample": "{ \"mcpServers\": { \"dre\": { \"command\": \"npx\", \"args\": [\"-y\",\"dre-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "branch-thinking",
			"name":          "Branch Thinking",
			"description":   "Manage multiple reasoning branches.",
			"category":      "Reasoning",
			"tags":          []string{"reasoning", "branches", "planning"},
			"version":       "1.0.0",
			"author":        "MCP Community",
			"repository":    "https://glama.ai/mcp/BranchThinking",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "branch-thinking-mcp"},
			"configExample": "{ \"mcpServers\": { \"branch-thinking\": { \"command\": \"npx\", \"args\": [\"-y\",\"branch-thinking-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "cot",
			"name":          "Chain-of-Thought (beverm2391)",
			"description":   "Exposes CoT tokens.",
			"category":      "Reasoning",
			"tags":          []string{"reasoning", "cot", "tokens"},
			"version":       "1.0.0",
			"author":        "MCP Community",
			"repository":    "https://github.com/beverm2391/cot-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "cot-mcp"},
			"configExample": "{ \"mcpServers\": { \"cot\": { \"command\": \"npx\", \"args\": [\"-y\",\"cot-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "cot-task",
			"name":          "CoT Task Manager",
			"description":   "Task decomposition with CoT.",
			"category":      "Reasoning",
			"tags":          []string{"reasoning", "cot", "tasks"},
			"version":       "1.0.0",
			"author":        "MCP Community",
			"repository":    "https://github.com/liorfranko/cot-task-manager",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "cot-task-mcp"},
			"configExample": "{ \"mcpServers\": { \"cot-task\": { \"command\": \"npx\", \"args\": [\"-y\",\"cot-task-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "planner",
			"name":          "Software Planner",
			"description":   "Software project planning.",
			"category":      "Reasoning",
			"tags":          []string{"reasoning", "planning", "software"},
			"version":       "1.0.0",
			"author":        "MCP Team",
			"repository":    "https://github.com/modelcontextprotocol/planner-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "planner-mcp"},
			"configExample": "{ \"mcpServers\": { \"planner\": { \"command\": \"npx\", \"args\": [\"-y\",\"planner-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "memory",
			"name":          "Memory MCP",
			"description":   "Persistent knowledge graph memory.",
			"category":      "Reasoning",
			"tags":          []string{"reasoning", "memory", "knowledge-graph"},
			"version":       "1.0.0",
			"author":        "MCP Team",
			"repository":    "https://github.com/modelcontextprotocol/memory-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "memory-mcp"},
			"configExample": "{ \"mcpServers\": { \"memory\": { \"command\": \"npx\", \"args\": [\"-y\",\"memory-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "mindmap",
			"name":          "Mindmap MCP",
			"description":   "Convert ideas into mindmaps.",
			"category":      "Reasoning",
			"tags":          []string{"reasoning", "mindmap", "visualization"},
			"version":       "1.0.0",
			"author":        "MCP Team",
			"repository":    "https://github.com/modelcontextprotocol/mindmap-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "mindmap-mcp"},
			"configExample": "{ \"mcpServers\": { \"mindmap\": { \"command\": \"npx\", \"args\": [\"-y\",\"mindmap-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "context-crystallizer",
			"name":          "Context Crystallizer",
			"description":   "Distill docs/repos into structured knowledge.",
			"category":      "Reasoning",
			"tags":          []string{"reasoning", "context", "knowledge"},
			"version":       "1.0.0",
			"author":        "MCP Team",
			"repository":    "https://github.com/modelcontextprotocol/context-crystallizer-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "context-crystallizer-mcp"},
			"configExample": "{ \"mcpServers\": { \"context-crystallizer\": { \"command\": \"npx\", \"args\": [\"-y\",\"context-crystallizer-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		// UI / Frontend
		{
			"slug":          "shadcn-ui",
			"name":          "Shadcn UI MCP",
			"description":   "Search/install shadcn/ui components.",
			"category":      "UI / Frontend",
			"tags":          []string{"ui", "frontend", "components"},
			"version":       "1.0.0",
			"author":        "MCP Community",
			"repository":    "https://github.com/Jpisnice/shadcn-ui-mcp-server",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "shadcn-ui-mcp-server"},
			"configExample": "{ \"mcpServers\": { \"shadcn-ui\": { \"command\": \"npx\", \"args\": [\"-y\",\"shadcn-ui-mcp-server\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "assistant-ui-docs",
			"name":          "assistant-ui Docs MCP",
			"description":   "Assistant-ui docs/examples in IDE.",
			"category":      "UI / Frontend Docs",
			"tags":          []string{"ui", "frontend", "docs", "ide"},
			"version":       "1.0.0",
			"author":        "Assistant UI Team",
			"repository":    "https://github.com/assistant-ui/mcp-docs",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "@assistant-ui/mcp-docs-server"},
			"configExample": "{ \"mcpServers\": { \"assistant-ui-docs\": { \"command\": \"npx\", \"args\": [\"-y\",\"@assistant-ui/mcp-docs-server\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		// Hosting / Infra
		{
			"slug":          "render",
			"name":          "Render MCP",
			"description":   "Manage Render services/deploys.",
			"category":      "Hosting / Infra",
			"tags":          []string{"hosting", "infrastructure", "render"},
			"version":       "1.0.0",
			"author":        "Render",
			"repository":    "https://github.com/render-oss/render-mcp-server",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "render-mcp-server"},
			"remote":        map[string]interface{}{"apiEndpoint": "https://mcp.render.com/mcp", "provider": "Render", "authType": "api_key"},
			"configExample": "{ \"mcpServers\": { \"render\": { \"url\": \"https://mcp.render.com/mcp\", \"headers\": { \"Authorization\": \"Bearer <RENDER_API_KEY>\" } } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "flyio",
			"name":          "Fly.io MCP",
			"description":   "Manage Fly.io apps via flyctl.",
			"category":      "Hosting / Infra",
			"tags":          []string{"hosting", "infrastructure", "flyio"},
			"version":       "1.0.0",
			"author":        "Fly.io",
			"repository":    "https://github.com/superfly/flymcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "flymcp"},
			"configExample": "{ \"mcpServers\": { \"flyio\": { \"command\": \"fly\", \"args\": [\"mcp\",\"server\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		// Cloud
		{
			"slug":          "aws-ccapi",
			"name":          "AWS CCAPI MCP",
			"description":   "Natural language AWS resource management.",
			"category":      "Cloud",
			"tags":          []string{"aws", "cloud", "infrastructure"},
			"version":       "1.0.0",
			"author":        "AWS Labs",
			"repository":    "https://github.com/awslabs/mcp",
			"license":       "Apache-2.0",
			"install":       map[string]string{"type": "npm", "uri": "@awslabs/ccapi-mcp-server"},
			"configExample": "{ \"mcpServers\": { \"aws-ccapi\": { \"command\": \"npx\", \"args\": [\"-y\",\"@awslabs/ccapi-mcp-server\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "aws-serverless",
			"name":          "AWS Serverless MCP",
			"description":   "Lambda/serverless guidance.",
			"category":      "Cloud",
			"tags":          []string{"aws", "cloud", "serverless"},
			"version":       "1.0.0",
			"author":        "AWS Labs",
			"repository":    "https://github.com/awslabs/mcp-serverless",
			"license":       "Apache-2.0",
			"install":       map[string]string{"type": "npm", "uri": "aws-serverless-mcp"},
			"configExample": "{ \"mcpServers\": { \"aws-serverless\": { \"command\": \"npx\", \"args\": [\"-y\",\"aws-serverless-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "gcp",
			"name":          "GCP MCP",
			"description":   "Google Cloud Platform.",
			"category":      "Cloud",
			"tags":          []string{"gcp", "cloud", "google"},
			"version":       "1.0.0",
			"author":        "MCP Community",
			"repository":    "https://github.com/devinschumacher/gcp-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "gcp-mcp"},
			"configExample": "{ \"mcpServers\": { \"gcp\": { \"command\": \"npx\", \"args\": [\"-y\",\"gcp-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "azure",
			"name":          "Azure MCP",
			"description":   "Manage Azure/DevOps.",
			"category":      "Cloud",
			"tags":          []string{"azure", "cloud", "microsoft"},
			"version":       "1.0.0",
			"author":        "MCP Community",
			"repository":    "https://github.com/devinschumacher/azure-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "azure-mcp"},
			"configExample": "{ \"mcpServers\": { \"azure\": { \"command\": \"npx\", \"args\": [\"-y\",\"azure-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "supabase",
			"name":          "Supabase MCP",
			"description":   "Manage Supabase DB/projects.",
			"category":      "Cloud / DB",
			"tags":          []string{"supabase", "database", "cloud"},
			"version":       "1.0.0",
			"author":        "Supabase Community",
			"repository":    "https://github.com/supabase-community/supabase-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "supabase-mcp"},
			"configExample": "{ \"mcpServers\": { \"supabase\": { \"command\": \"npx\", \"args\": [\"-y\",\"supabase-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		// Dev
		{
			"slug":          "github",
			"name":          "GitHub MCP",
			"description":   "Manage issues, PRs, repos.",
			"category":      "Dev",
			"tags":          []string{"github", "git", "api"},
			"version":       "1.0.0",
			"author":        "GitHub",
			"repository":    "https://github.com/github/github-mcp-server",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "github-mcp"},
			"remote":        map[string]interface{}{"apiEndpoint": "https://api.githubcopilot.com/mcp/", "provider": "GitHub", "authType": "oauth2"},
			"configExample": "{ \"servers\": { \"github\": { \"type\": \"http\", \"url\": \"https://api.githubcopilot.com/mcp/\" } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "figma",
			"name":          "Figma MCP",
			"description":   "Extract assets, metadata.",
			"category":      "Design",
			"tags":          []string{"design", "figma", "assets"},
			"version":       "1.0.0",
			"author":        "MCP Team",
			"repository":    "https://github.com/modelcontextprotocol/figma-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "figma-mcp"},
			"configExample": "{ \"mcpServers\": { \"figma\": { \"command\": \"npx\", \"args\": [\"-y\",\"figma-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		// Comms
		{
			"slug":          "slack",
			"name":          "Slack MCP",
			"description":   "Read, post, and search Slack messages and channels.",
			"category":      "Comms",
			"tags":          []string{"slack", "communication", "messaging"},
			"version":       "1.0.0",
			"author":        "MCP Community",
			"repository":    "https://github.com/augmentcode/slack-mcp-server",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "slack-mcp-server"},
			"configExample": "{ \"mcpServers\": { \"slack\": { \"command\": \"npx\", \"args\": [\"-y\",\"slack-mcp-server\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		// Email
		{
			"slug":          "gmail",
			"name":          "Gmail MCP",
			"description":   "Read and write Gmail messages.",
			"category":      "Email",
			"tags":          []string{"gmail", "email", "google"},
			"version":       "1.0.0",
			"author":        "MCP Community",
			"repository":    "https://github.com/GongRzhe/Gmail-MCP-Server",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "gmail-mcp-server"},
			"configExample": "{ \"mcpServers\": { \"gmail\": { \"command\": \"npx\", \"args\": [\"-y\",\"gmail-mcp-server\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		// Docs
		{
			"slug":          "gdocs",
			"name":          "Google Docs MCP",
			"description":   "Query/edit Docs.",
			"category":      "Docs",
			"tags":          []string{"docs", "google", "collaboration"},
			"version":       "1.0.0",
			"author":        "MCP Team",
			"repository":    "https://github.com/modelcontextprotocol/google-docs-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "git", "uri": "https://github.com/modelcontextprotocol/google-docs-mcp"},
			"configExample": "{ \"mcpServers\": { \"gdocs\": { \"command\": \"node\", \"args\": [\"server.js\"], \"env\":{ \"GOOGLE_APPLICATION_CREDENTIALS\":\"./credentials.json\" } } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		// Calendar
		{
			"slug":          "gcal",
			"name":          "Google Calendar MCP",
			"description":   "Manage events.",
			"category":      "Calendar",
			"tags":          []string{"calendar", "google", "events"},
			"version":       "1.0.0",
			"author":        "MCP Team",
			"repository":    "https://github.com/modelcontextprotocol/google-calendar-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "git", "uri": "https://github.com/modelcontextprotocol/google-calendar-mcp"},
			"configExample": "{ \"mcpServers\": { \"gcal\": { \"command\": \"node\", \"args\": [\"index.js\"], \"env\":{ \"GOOGLE_CLIENT_ID\":\"...\",\"GOOGLE_CLIENT_SECRET\":\"...\" } } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		// Notes
		{
			"slug":          "notion",
			"name":          "Notion MCP",
			"description":   "Manage Notion databases and pages.",
			"category":      "Notes",
			"tags":          []string{"notion", "database", "notes"},
			"version":       "1.0.0",
			"author":        "Notion",
			"repository":    "https://github.com/makenotion/notion-mcp-server",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "@notionhq/notion-mcp-server"},
			"remote":        map[string]interface{}{"apiEndpoint": "https://mcp.notion.com/mcp", "provider": "Notion", "authType": "oauth2"},
			"configExample": "{ \"mcpServers\": { \"Notion\": { \"url\": \"https://mcp.notion.com/mcp\" } } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		// Social
		{
			"slug":          "youtube",
			"name":          "YouTube MCP",
			"description":   "Query/fetch YouTube metadata.",
			"category":      "Social",
			"tags":          []string{"youtube", "video", "metadata"},
			"version":       "1.0.0",
			"author":        "MCP Team",
			"repository":    "https://github.com/modelcontextprotocol/youtube-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "git", "uri": "https://github.com/modelcontextprotocol/youtube-mcp"},
			"configExample": "{ \"mcpServers\": { \"youtube\": { \"command\": \"node\", \"args\": [\"server.js\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "twitter",
			"name":          "TweetBinder MCP",
			"description":   "Twitter analytics.",
			"category":      "Social",
			"tags":          []string{"twitter", "analytics", "social"},
			"version":       "1.0.0",
			"author":        "MCP Team",
			"repository":    "https://github.com/modelcontextprotocol/tweetbinder-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "tweetbinder-mcp"},
			"configExample": "{ \"mcpServers\": { \"twitter\": { \"command\": \"npx\", \"args\": [\"-y\",\"tweetbinder-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		// Messaging
		{
			"slug":          "telegram",
			"name":          "Telegram MCP",
			"description":   "Messaging integration.",
			"category":      "Messaging",
			"tags":          []string{"telegram", "messaging", "chat"},
			"version":       "1.0.0",
			"author":        "MCP Team",
			"repository":    "https://github.com/modelcontextprotocol/telegram-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "telegram-mcp"},
			"configExample": "{ \"mcpServers\": { \"telegram\": { \"command\": \"npx\", \"args\": [\"-y\",\"telegram-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		// Social / Newsletters
		{
			"slug":          "substack",
			"name":          "Substack MCP",
			"description":   "Manage Substack posts.",
			"category":      "Social / Newsletters",
			"tags":          []string{"substack", "newsletter", "publishing"},
			"version":       "1.0.0",
			"author":        "MCP Team",
			"repository":    "https://github.com/modelcontextprotocol/substack-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "substack-mcp"},
			"configExample": "{ \"mcpServers\": { \"substack\": { \"command\": \"npx\", \"args\": [\"-y\",\"substack-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		// Containers
		{
			"slug":          "docker",
			"name":          "Docker MCP",
			"description":   "Manage Docker containers and images.",
			"category":      "Containers",
			"tags":          []string{"docker", "containers", "devops"},
			"version":       "1.0.0",
			"author":        "MCP Community",
			"repository":    "https://github.com/docker-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "docker-mcp"},
			"configExample": "{ \"mcpServers\": { \"docker\": { \"command\": \"npx\", \"args\": [\"-y\",\"docker-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		// Infra as Code
		{
			"slug":          "terraform",
			"name":          "Terraform MCP",
			"description":   "Terraform plan/apply via LLM.",
			"category":      "Infra as Code",
			"tags":          []string{"terraform", "infrastructure", "iac"},
			"version":       "1.0.0",
			"author":        "MCP Community",
			"repository":    "https://github.com/devinschumacher/tfmcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "tfmcp"},
			"configExample": "{ \"mcpServers\": { \"terraform\": { \"command\": \"npx\", \"args\": [\"-y\",\"tfmcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		// Monitoring
		{
			"slug":          "prometheus",
			"name":          "Prometheus MCP",
			"description":   "Query Prometheus metrics.",
			"category":      "Monitoring",
			"tags":          []string{"prometheus", "monitoring", "metrics"},
			"version":       "1.0.0",
			"author":        "MCP Team",
			"repository":    "https://github.com/modelcontextprotocol/prometheus-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "prometheus-mcp"},
			"configExample": "{ \"mcpServers\": { \"prometheus\": { \"command\": \"npx\", \"args\": [\"-y\",\"prometheus-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		// Security / Recon
		{
			"slug":          "shodan",
			"name":          "Shodan MCP",
			"description":   "Shodan scans & OSINT.",
			"category":      "Security / Recon",
			"tags":          []string{"shodan", "security", "osint"},
			"version":       "1.0.0",
			"author":        "MCP Team",
			"repository":    "https://github.com/modelcontextprotocol/shodan-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "shodan-mcp"},
			"configExample": "{ \"mcpServers\": { \"shodan\": { \"command\": \"npx\", \"args\": [\"-y\",\"shodan-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
		{
			"slug":          "nmap",
			"name":          "Nmap MCP",
			"description":   "Network scanning.",
			"category":      "Security / Net",
			"tags":          []string{"nmap", "security", "network"},
			"version":       "1.0.0",
			"author":        "MCP Team",
			"repository":    "https://github.com/modelcontextprotocol/nmap-mcp",
			"license":       "MIT",
			"install":       map[string]string{"type": "npm", "uri": "nmap-mcp"},
			"configExample": "{ \"mcpServers\": { \"nmap\": { \"command\": \"npx\", \"args\": [\"-y\",\"nmap-mcp\"] } } }",
			"createdAt":     "2024-01-01T00:00:00Z",
			"updatedAt":     "2024-01-01T00:00:00Z",
		},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(marketplaceItems)
}
